USE tienda;
SELECT * FROM producto;
SELECT nombre, precio FROM producto;
SELECT codigo,nombre,precio, codigo_fabricante FROM producto;
SELECT nombre, precio, precio * 1.09 FROM producto;
SELECT nombre AS 'Nombre de producto', precio AS Euros, precio * 1.09 AS Dólares FROM producto;
SELECT UPPER (nombre), precio FROM producto;
SELECT LOWER (nombre), precio FROM producto;
SELECT nombre, SUBSTRING(nombre, 1,2) AS Iniciales FROM fabricante;
SELECT nombre, ROUND (precio,1) FROM producto;
SELECT nombre, ROUND (precio,0) FROM producto;
SELECT codigo_fabricante FROM producto JOIN fabricante ON fabricante.codigo = producto.codigo_fabricante;
SELECT DISTINCT codigo_fabricante FROM producto JOIN fabricante ON fabricante.codigo = producto.codigo_fabricante;
SELECT nombre FROM fabricante ORDER BY nombre;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre FROM fabricante ORDER BY nombre, nombre DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 3,2;
SELECT nombre, precio FROM producto ORDER BY precio LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT DISTINCT producto.nombre FROM producto JOIN fabricante ON codigo_fabricante = 2;
